# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cac0e1708bccaa082a7c09bd2cf139efe6c3d86337e00997a5d9145055ae4c80671c0f4bbc85ae2ab41ef518cb89a9c8b0fbd835e3a5fed05a2a45db600b894b

test:
  secret_key_base: f08073d8330a2ed8e44e44d636625a00ac470ffdd22c9509f987bd2c7a0448319440f81212ebc8ea2f336a747ca9950d5b039cfc1be3e6ae3b8ead027d427b8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
