# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7e4635f9ba43c560566d91b299c537adb46e9153e3f72bdcecdaa8e40cf35536fe943471bc53f4db47b36b4ea7e7ab06e2f8514ad6459669fde45fd9e76035c

test:
  secret_key_base: d86a081908b732c81338ca78fe8b52299ca647ae22ddfc1e1e1ef04d8a9c54e5c1f3fdb9b7a1376080e21968f1ecee0c5e94c29243e43c0a1db1b8941d41cee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
